"""allergens table

Revision ID: 1426145c8a26
Revises: f9e7798548d4
Create Date: 2022-08-06 20:23:16.038339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1426145c8a26'
down_revision = 'f9e7798548d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergen',
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.Column('allergenName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('allergen_id'),
    sa.UniqueConstraint('allergenName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allergen')
    # ### end Alembic commands ###
