"""remove address fields from doctor

Revision ID: 2c59806908cb
Revises: 7284864abda1
Create Date: 2022-08-10 20:55:15.889830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c59806908cb'
down_revision = '7284864abda1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_index('ix_doctor_postcode')
        batch_op.drop_index('ix_doctor_streetName')
        batch_op.drop_column('houseNo')
        batch_op.drop_column('streetName')
        batch_op.drop_column('postcode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postcode', sa.VARCHAR(length=7), nullable=True))
        batch_op.add_column(sa.Column('streetName', sa.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('houseNo', sa.VARCHAR(length=5), nullable=True))
        batch_op.create_index('ix_doctor_streetName', ['streetName'], unique=False)
        batch_op.create_index('ix_doctor_postcode', ['postcode'], unique=False)

    # ### end Alembic commands ###
