"""appointments1

Revision ID: 36bc0ee95801
Revises: 3b92d13dc96d
Create Date: 2022-09-15 08:47:57.855744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36bc0ee95801'
down_revision = '3b92d13dc96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index('ix_appointment_dateTime')
        batch_op.drop_column('dateTime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateTime', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_appointment_dateTime', ['dateTime'], unique=False)

    # ### end Alembic commands ###
