"""diseases table

Revision ID: 39958b78e270
Revises: 29fddc399a19
Create Date: 2022-08-06 23:11:09.037858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39958b78e270'
down_revision = '29fddc399a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease',
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('diseaseName', sa.String(length=128), nullable=True),
    sa.Column('inheritability', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('disease_id')
    )
    op.create_index(op.f('ix_disease_diseaseName'), 'disease', ['diseaseName'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disease_diseaseName'), table_name='disease')
    op.drop_table('disease')
    # ### end Alembic commands ###
