"""prescriptions table

Revision ID: 402806fee1ee
Revises: eb7c2d3ac167
Create Date: 2022-08-10 22:31:35.936080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402806fee1ee'
down_revision = 'eb7c2d3ac167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescription',
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('med_id', sa.Integer(), nullable=True),
    sa.Column('NHSNumber', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('dose', sa.String(length=2048), nullable=True),
    sa.Column('finalRepeatDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['NHSNumber'], ['patient.NHSNumber'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.ForeignKeyConstraint(['med_id'], ['medicine.med_id'], ),
    sa.PrimaryKeyConstraint('prescription_id')
    )
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_startDate'), ['startDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescription_finalRepeatDate'), ['finalRepeatDate'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_startDate'))

    op.drop_table('prescription')
    # ### end Alembic commands ###
