"""addresses table

Revision ID: 417f5bdaac00
Revises: 4bfaef5252a8
Create Date: 2022-08-08 18:10:29.525577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417f5bdaac00'
down_revision = '4bfaef5252a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('houseNo', sa.String(length=5), nullable=True),
    sa.Column('streetName', sa.String(length=36), nullable=True),
    sa.Column('postcode', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_index(op.f('ix_address_postcode'), 'address', ['postcode'], unique=False)
    op.create_index(op.f('ix_address_streetName'), 'address', ['streetName'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_streetName'), table_name='address')
    op.drop_index(op.f('ix_address_postcode'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
