"""remove patient.streetName

Revision ID: 5ae4f3db615b
Revises: dfe7961eff9e
Create Date: 2022-08-10 17:23:55.687952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae4f3db615b'
down_revision = 'dfe7961eff9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_streetName')
        batch_op.drop_column('streetName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streetName', sa.VARCHAR(length=36), nullable=True))
        batch_op.create_index('ix_patient_streetName', ['streetName'], unique=False)

    # ### end Alembic commands ###
