"""remove patient.postcode

Revision ID: 60d0d1233a1c
Revises: 5ae4f3db615b
Create Date: 2022-08-10 17:28:42.573640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d0d1233a1c'
down_revision = '5ae4f3db615b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_postcode')
        batch_op.drop_column('postcode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postcode', sa.VARCHAR(length=7), nullable=True))
        batch_op.create_index('ix_patient_postcode', ['postcode'], unique=False)

    # ### end Alembic commands ###
