"""tblDoctors

Revision ID: 7f533775308a
Revises: 
Create Date: 2022-07-05 17:41:50.645727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f533775308a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('accessLev', sa.Integer(), nullable=True),
    sa.Column('NINumber', sa.String(length=9), nullable=True),
    sa.Column('forename', sa.String(length=30), nullable=True),
    sa.Column('surname', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('houseNo', sa.String(length=5), nullable=True),
    sa.Column('streetName', sa.String(length=36), nullable=True),
    sa.Column('postcode', sa.String(length=7), nullable=True),
    sa.Column('passwordHash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_index(op.f('ix_doctor_NINumber'), 'doctor', ['NINumber'], unique=True)
    op.create_index(op.f('ix_doctor_accessLev'), 'doctor', ['accessLev'], unique=False)
    op.create_index(op.f('ix_doctor_email'), 'doctor', ['email'], unique=True)
    op.create_index(op.f('ix_doctor_forename'), 'doctor', ['forename'], unique=False)
    op.create_index(op.f('ix_doctor_gender'), 'doctor', ['gender'], unique=False)
    op.create_index(op.f('ix_doctor_passwordHash'), 'doctor', ['passwordHash'], unique=False)
    op.create_index(op.f('ix_doctor_postcode'), 'doctor', ['postcode'], unique=False)
    op.create_index(op.f('ix_doctor_streetName'), 'doctor', ['streetName'], unique=False)
    op.create_index(op.f('ix_doctor_surname'), 'doctor', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_surname'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_streetName'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_postcode'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_passwordHash'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_gender'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_forename'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_email'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_accessLev'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_NINumber'), table_name='doctor')
    op.drop_table('doctor')
    # ### end Alembic commands ###
