"""appointment table

Revision ID: 8393d47dbd57
Revises: 402806fee1ee
Create Date: 2022-08-10 22:47:03.775137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8393d47dbd57'
down_revision = '402806fee1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('NHSNumber', sa.Integer(), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.Column('room', sa.String(length=64), nullable=True),
    sa.Column('fulfilled', sa.Boolean(), nullable=True),
    sa.Column('patient_feedback', sa.String(length=1024), nullable=True),
    sa.Column('doctorNotes', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['NHSNumber'], ['patient.NHSNumber'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_dateTime'), ['dateTime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_dateTime'))

    op.drop_table('appointment')
    # ### end Alembic commands ###
