"""upgrade patient

Revision ID: 97d58d6a213a
Revises: a5398b57c983
Create Date: 2022-08-21 19:57:33.882460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d58d6a213a'
down_revision = 'a5398b57c983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_email')
        batch_op.create_index(batch_op.f('ix_patient_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_email'))
        batch_op.create_index('ix_patient_email', ['email'], unique=False)

    # ### end Alembic commands ###
