"""test, illness history, referral tables

Revision ID: a5398b57c983
Revises: 8393d47dbd57
Create Date: 2022-08-10 22:55:16.443050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5398b57c983'
down_revision = '8393d47dbd57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('illness_history',
    sa.Column('unhealthy_id', sa.Integer(), nullable=False),
    sa.Column('NHSNumber', sa.Integer(), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.Column('diagnosisDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['NHSNumber'], ['patient.NHSNumber'], ),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.disease_id'], ),
    sa.PrimaryKeyConstraint('unhealthy_id')
    )
    with op.batch_alter_table('illness_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_illness_history_diagnosisDate'), ['diagnosisDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_illness_history_endDate'), ['endDate'], unique=False)

    op.create_table('referral',
    sa.Column('referral_id', sa.Integer(), nullable=False),
    sa.Column('NHSNumber', sa.Integer(), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.Column('diagnosisDate', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['NHSNumber'], ['patient.NHSNumber'], ),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.disease_id'], ),
    sa.PrimaryKeyConstraint('referral_id')
    )
    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referral_diagnosisDate'), ['diagnosisDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_type'), ['type'], unique=False)

    op.create_table('test',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('NHSNumber', sa.Integer(), nullable=True),
    sa.Column('testDate', sa.Date(), nullable=True),
    sa.Column('testType', sa.String(length=64), nullable=True),
    sa.Column('testDoctorNotes', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['NHSNumber'], ['patient.NHSNumber'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.PrimaryKeyConstraint('test_id')
    )
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_testDate'), ['testDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_testType'), ['testType'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_testType'))
        batch_op.drop_index(batch_op.f('ix_test_testDate'))

    op.drop_table('test')
    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_type'))
        batch_op.drop_index(batch_op.f('ix_referral_diagnosisDate'))

    op.drop_table('referral')
    with op.batch_alter_table('illness_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_illness_history_endDate'))
        batch_op.drop_index(batch_op.f('ix_illness_history_diagnosisDate'))

    op.drop_table('illness_history')
    # ### end Alembic commands ###
