"""remove patient.houseNo

Revision ID: dfe7961eff9e
Revises: 417f5bdaac00
Create Date: 2022-08-10 13:44:42.507819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe7961eff9e'
down_revision = '417f5bdaac00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('houseNo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('houseNo', sa.VARCHAR(length=5), nullable=True))

    # ### end Alembic commands ###
