"""allergies table

Revision ID: eb7c2d3ac167
Revises: a8e10f5dd893
Create Date: 2022-08-10 21:53:32.216169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7c2d3ac167'
down_revision = 'a8e10f5dd893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergy',
    sa.Column('patientAllergy_id', sa.Integer(), nullable=False),
    sa.Column('NHSNumber', sa.Integer(), nullable=True),
    sa.Column('allergen_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['NHSNumber'], ['patient.NHSNumber'], ),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergen.allergen_id'], ),
    sa.PrimaryKeyConstraint('patientAllergy_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allergy')
    # ### end Alembic commands ###
