"""hoursSpent table

Revision ID: f9e7798548d4
Revises: e21f80c52032
Create Date: 2022-07-07 21:22:09.451450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e7798548d4'
down_revision = 'e21f80c52032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hours_spent',
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('entryTime', sa.Time(), nullable=True),
    sa.Column('leaveTime', sa.Time(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hours_spent')
    # ### end Alembic commands ###
